Add B+/Bd lifetime ratio as observable
flav-io/flavio pull request #261
Opened 2024-11-12 14:28 UTC by MJKirk

Includes contributions from (sbar b)(cbar c), (sbar b)(cbar u) and (dbar b)(cbar u) operators.

Requires merging my wilson PR (https://github.com/wilson-eft/wilson/pull/116) so the sbcu and dbcu sectors are available

2025-04-23 17:28 UTC, peterstangl requested changes
I think we should require wilson v2.5 to make sure the new WET sectors are available:

https://github.com/flav-io/flavio/blob/4eca6c8883edb8bc80586254176339a9142b0264/setup.py#L35-L36

2025-04-23 17:47 UTC, peterstangl requested changes

2025-04-23 17:47 UTC, peterstangl commented on flavio/physics/bdecays/lifetime_ratio.py
> +    ))
Maybe this could be made a bit more readable by creating the array from a list instead of a tuple, and by adding line breaks and indentation similar to the following example:
```python
    A_WE_cu = np.array([
        [
            (-((2 + rho)*me["1"]) + 2*(me["2"] + 2*rho*me["2"] - 3*(2 + rho)*me["3"] + 6*(me["4"] + 2*rho*me["4"])))/6,
            -((2 + rho)*me["1"])/2 + me["2"] + 2*rho*me["2"],
            -(rho**0.5*(me["2"] + 6*me["4"])),
            -3*rho**0.5*me["2"],
            0,0,0,0,0,0,0,0,0,0,
            ((2 + rho)*me["5p"] - 2*(me["6p"] + 2*rho*me["6p"] - 3*(2 + rho)*me["7p"] + 6*(me["8p"] + 2*rho*me["8p"])))/12,
            ((2 + rho)*me["5p"] - 2*(me["6p"] + 2*rho*me["6p"]))/4,
            (rho**0.5*(me["5p"] - 2*(me["6p"] - 3*me["7p"] + 6*me["8p"])))/4,
            (3*rho**0.5*(me["5p"] - 2*me["6p"]))/4,
            -(rho**0.5*(me["5p"] + 2*(me["6p"] + 3*me["7p"] + 6*me["8p"]))),
            -3*rho**0.5*(me["5p"] + 2*me["6p"]),
        ],
        [
            -((2 + rho)*me["1"])/2 + me["2"] + 2*rho*me["2"],
            (-3*(2 + rho)*me["1"])/2 + 3*(1 + 2*rho)*me["2"],
            -3*rho**0.5*me["2"],
            -9*rho**0.5*me["2"],
            0,0,0,0,0,0,0,0,0,0,
            ((2 + rho)*me["5p"] - 2*(me["6p"] + 2*rho*me["6p"]))/4,
            (3*((2 + rho)*me["5p"] - 2*(me["6p"] + 2*rho*me["6p"])))/4,
            (3*rho**0.5*(me["5p"] - 2*me["6p"]))/4,
            (9*rho**0.5*(me["5p"] - 2*me["6p"]))/4,
            -3*rho**0.5*(me["5p"] + 2*me["6p"]),
            -9*rho**0.5*(me["5p"] + 2*me["6p"]),
        ],
        [
            -(rho**0.5*(me["2"] + 6*me["4"])),
            -3*rho**0.5*me["2"],
            2*(me["2"] + 6*me["4"]),
            6*me["2"],
            0,0,0,0,0,0,0,0,0,0,
            (rho**0.5*(me["6p"] + 6*me["8p"]))/2,
            (3*rho**0.5*me["6p"])/2,
            (me["6p"] + 6*me["8p"])/2,
            (3*me["6p"])/2,
            6*(me["6p"] + 6*me["8p"]),
            18*me["6p"],
        ],
        ...
```

2025-04-23 17:47 UTC, peterstangl commented on flavio/physics/bdecays/lifetime_ratio.py
> +    ))
Same comment as above concerning readability.

2025-04-23 17:47 UTC, peterstangl commented on flavio/physics/bdecays/lifetime_ratio.py
> +    ))
Same comment as above concerning readability.

2025-04-23 17:47 UTC, peterstangl commented on flavio/physics/bdecays/lifetime_ratio.py
> +    return ratio_SM
Why is this phenomenological formula used here instead of the full expression? If possible, I think the full expression should always be used to allow for changes in the input parameters.

2025-04-23 17:47 UTC, peterstangl commented on flavio/physics/bdecays/test_lifetime_ratio.py
> +        self.assertAlmostEqual(flavio.np_prediction("tau_B+/tau_Bd", wc), 1.085435224)
Could it make sense to also test the size of the uncertainties in addition to the central values?

2025-04-24 15:33 UTC, MJKirk commented on flavio/physics/bdecays/lifetime_ratio.py
> +    ))
Yes, that's probably nicer. I also considered whether it might be better to move these matrices off into a separate python file to keep this main file a bit cleaner, what do you think? (Also thinking a bit of the future if I/someone implements that contributions from many sectors, this could easily get huge)

2025-04-24 15:49 UTC, MJKirk commented on flavio/physics/bdecays/lifetime_ratio.py
> +    return ratio_SM
Short answer: Because that's what I have access to.
Some justification: If you look at fig 5 in [2208.02643](https://arxiv.org/abs/2208.02643) you see that the SM uncertainty is ~75% coming from the bag parameters central values, and most of the rest is from $\mu_0$, which is the RG running of those values from the low scale where they are determined up to the B scale. So as long as you don't want to vary the other input parameters far outside their current uncertainties, this formula is valid.
Certainly it would be better to have the full formula, but I'd have to put it togther myself or ask Alex (or Maria Laura probably) if he has a notebook with everything in

2025-04-24 15:53 UTC, MJKirk commented on flavio/physics/bdecays/test_lifetime_ratio.py
> +        self.assertAlmostEqual(flavio.np_prediction("tau_B+/tau_Bd", wc), 1.085435224)
Yes, good idea

2025-04-24 19:01 UTC, DavidMStraub commented on flavio/physics/bdecays/lifetime_ratio.py
> +    ))
+1 for formatting, I would just format this entire file with `black`.

As for encapsulation, whether this thing is put into a separate module or not is secondary I would say, but it definitely should be a separate *function* (and have separate unit tests if possible...).

Something I would personally do (but up to you if you agree or not) is to use a `dataclass` instead of a `dict` for the lifetime matrix elements and the bag parameters. Although setting 18 parameters on it explicitly might seem less elegant than the for loop, it is more eplicit and easier for the type checker to understand than a dict with string keys.

2025-11-13 16:55 UTC, MJKirk commented on flavio/physics/bdecays/test_lifetime_ratio.py
> +    def test_A_WE_cu(self):
Add comment about what A_WE_cu is

2025-11-13 16:55 UTC, MJKirk commented on flavio/physics/bdecays/test_lifetime_ratio.py
> +    def test_A_PI_cd(self):
Ditto

2025-11-13 16:56 UTC, MJKirk commented on flavio/physics/bdecays/lifetime_ratio.py
> +    if scale < config["RGE thresholds"]["mc"] or scale > 4.5:
Add some delta around the limits of the running

2025-11-13 18:05 UTC, peterstangl approved these changes

2025-11-13 18:06 UTC, merged